-- Chronos Drift Visualizer: PostgreSQL Schema
-- Optimized for high-frequency time-series execution jitter and clock drift data.
-- Utilizes partitioning strategies for high-throughput ingestion and forensic analysis.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Enum for service health status based on drift thresholds
DO $$ BEGIN
    CREATE TYPE service_status AS ENUM ('synced', 'drifting', 'volatile', 'offline');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Table for system nodes/microservices participating in the cluster
CREATE TABLE IF NOT EXISTS cluster_nodes (
    node_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    service_name VARCHAR(255) NOT NULL,
    environment VARCHAR(50) NOT NULL DEFAULT 'production',
    host_ip INET NOT NULL,
    os_kernel VARCHAR(100),
    clock_source VARCHAR(50) DEFAULT 'tsc', -- e.g., kvm-clock, tsc, hpet
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Main measurements table partitioned by time (manually or via TimescaleDB if available)
-- This stores the raw drift and jitter data parsed from Zig binary collectors.
CREATE TABLE IF NOT EXISTS drift_metrics (
    observation_time TIMESTAMPTZ NOT NULL,
    source_node_id UUID NOT NULL REFERENCES cluster_nodes(node_id),
    target_node_id UUID REFERENCES cluster_nodes(node_id), -- NULL if measuring local jitter
    
    -- Precise values in nanoseconds (stored as BIGINT to prevent floating point errors)
    offset_ns BIGINT NOT NULL,
    jitter_ns BIGINT NOT NULL,
    round_trip_time_ns BIGINT,
    
    -- Execution delay between process cycles
    execution_drift_ns BIGINT,
    
    -- Contextual metadata for forensics
    cpu_usage_pct REAL,
    context_switches BIGINT,
    
    PRIMARY KEY (observation_time, source_node_id)
);

-- Specific index for WebGL heatmap queries (filtering by time and node clusters)
CREATE INDEX IF NOT EXISTS idx_drift_metrics_lookup 
ON drift_metrics (observation_time DESC, source_node_id);

-- Partitioning logic (Native PostgreSQL Declarative Partitioning)
-- Example for a single day; in production, these are generated by a background worker.
CREATE TABLE IF NOT EXISTS drift_metrics_template (LIKE drift_metrics INCLUDING ALL);

-- Table for long-term aggregated drift patterns for 3D visualization trends
CREATE TABLE IF NOT EXISTS drift_aggregates (
    bucket_start TIMESTAMPTZ NOT NULL,
    bucket_end TIMESTAMPTZ NOT NULL,
    node_id UUID NOT NULL REFERENCES cluster_nodes(node_id),
    
    avg_offset_ns DOUBLE PRECISION,
    max_offset_ns BIGINT,
    p95_offset_ns BIGINT,
    stddev_offset_ns DOUBLE PRECISION,
    
    sample_count BIGINT,
    
    PRIMARY KEY (bucket_start, node_id)
);

-- View for the WebGL frontend to fetch the current "state of the world"
CREATE OR REPLACE VIEW v_current_cluster_health AS
SELECT 
    n.service_name,
    n.host_ip,
    m.observation_time,
    m.offset_ns,
    m.jitter_ns,
    CASE 
        WHEN ABS(m.offset_ns) < 50000 THEN 'synced'::service_status
        WHEN ABS(m.offset_ns) BETWEEN 50000 AND 500000 THEN 'drifting'::service_status
        ELSE 'volatile'::service_status
    END as status
FROM cluster_nodes n
JOIN LATERAL (
    SELECT * FROM drift_metrics 
    WHERE source_node_id = n.node_id 
    ORDER BY observation_time DESC 
    LIMIT 1
) m ON TRUE;

-- Function to prune old records (Retention Policy)
CREATE OR REPLACE FUNCTION prune_old_drift_data(retention_interval INTERVAL) 
RETURNS VOID AS $$
BEGIN
    DELETE FROM drift_metrics WHERE observation_time < (NOW() - retention_interval);
    DELETE FROM drift_aggregates WHERE bucket_start < (NOW() - (retention_interval * 4));
END;
$$ LANGUAGE plpgsql;

-- Comments for documentation
COMMENT ON TABLE drift_metrics IS 'High-precision raw drift data ingested from Zig collectors';
COMMENT ON COLUMN drift_metrics.offset_ns IS 'Offset relative to reference clock in nanoseconds';
COMMENT ON COLUMN drift_metrics.jitter_ns IS 'Variation in latency between consecutive pulses';